name: pull-request

on:
  pull_request:
    branches:
      - main

env:
  VITE_APP_API_URL: ${{ vars.STAGING_API_URL }}

jobs:
  verify:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref_name }}-verify
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Check code quality
        shell: bash
        run: yarn run lint:check

      - name: Check formatting
        shell: bash
        run: yarn run format:check

  unit-test:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref_name }}-test
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Run unit tests
        shell: bash
        run: yarn run test
