name: push-main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref_name }}-verify
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Check code quality
        shell: bash
        run: yarn run lint:check

      - name: Check formatting
        shell: bash
        run: yarn run format:check

  test:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref_name }}-test
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Run the tests
        shell: bash
        run: yarn run test:coverage

      - name: Comment coverage on PR
        uses: davelosert/vitest-coverage-report-action@v1
        with:
          vitest-config-path: './vite.config.js'

  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref_name }}-build
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Build the app
        shell: bash
        run: yarn run build
